dataset_path: json
dataset_kwargs:
  data_files: lmms_eval/tasks/tcm_sd/dataset/tcm_sd_test_rc_all.json
task: tcm_sd_rc_all
test_split: train
output_type: generate_until
doc_to_text: !function utils.tcm_sd_doc_to_text_rc_all
doc_to_target: "expected_answer"
generation_kwargs:
  until:
    - "ASSISTANT:"
  max_new_tokens: 10
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.tcm_sd_process_results_rc_all
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
    ignore_numbers: true
  - metric: hit_rate
    aggregation: !function utils.tcm_sd_aggregate_results_hit_rate
    higher_is_better: true
metadata:
  version: 0.0
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "" 